### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by pssguy** [ramnathv/rbokeh#1]
- installing _source_ package 'rbokeh' ...
  *\* R
  *\* inst
  *\* preparing package for lazy loading
  Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'rCharts2'
  ERROR: lazy loading failed for package 'rbokeh'
- removing 'C:/Users/pssguy/Documents/R/win-library/3.1/rbokeh'

**Comment by pssguy** [comment]
Looks like line 5 of NAMESPACE
Amending to importFrom(rCharts,getLayer)

seems to fix it

**Comment by pachevalier** [comment]
Sure, I've replaced `rCharts2` with `rCharts` and it works !!! Have a look : https://github.com/blaquans/rbokeh/blob/master/NAMESPACE

**Comment by ramnathv** [comment]
I must have forgotten to update NAMESPACE after moving getLayer directly into the package. I just pushed a fix which should take care of it. Can you confirm that you are able to install now?

**Comment by pachevalier** [comment]
It works !
